In [3]:
import numpy as np

In [4]:
arr1 = np.array([1,2,3,4])

In [5]:
arr1

array([1, 2, 3, 4])

In [6]:
type(arr1)

numpy.ndarray

In [7]:
arr1.shape

(4,)

In [8]:
arr1.reshape(1,4)

array([[1, 2, 3, 4]])

In [9]:
arr2 = np.array([[1,2,3,4], [5,6,7,8]])

In [10]:
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
arr2.shape

(2, 4)

In [12]:
np.arange(1,16,2).reshape(2,-1)

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15]])

In [13]:
#uniform array
np.ones((2,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [14]:
#identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
#attributes of numpy
print(arr2.shape)
print(arr2.size)
print(arr2.ndim)
print(arr2.dtype)
print(arr2.itemsize)

(2, 4)
8
2
int32
4


In [16]:
#Universal functions
arr = np.arange(1,25,3).reshape(2,-1)
print(arr)
print(np.sqrt(arr))
print(np.sin(arr))
print(np.exp(arr))
print(np.log(arr))

[[ 1  4  7 10]
 [13 16 19 22]]
[[1.         2.         2.64575131 3.16227766]
 [3.60555128 4.         4.35889894 4.69041576]]
[[ 0.84147098 -0.7568025   0.6569866  -0.54402111]
 [ 0.42016704 -0.28790332  0.14987721 -0.00885131]]
[[2.71828183e+00 5.45981500e+01 1.09663316e+03 2.20264658e+04]
 [4.42413392e+05 8.88611052e+06 1.78482301e+08 3.58491285e+09]]
[[0.         1.38629436 1.94591015 2.30258509]
 [2.56494936 2.77258872 2.94443898 3.09104245]]


In [38]:
#Array slicig and indexing
print(arr[1,1:3])

[16 19]


In [42]:
#statistics
mean = np.mean(arr)
median = np.median(arr)
std_div = np.std(arr)
variance = np.var(arr)

In [44]:
print(mean)
print(median)
print(std_div)
print(variance)

11.5
11.5
6.87386354243376
47.25


In [48]:
#normalization
norm = (arr - mean) / std_div
print(norm)

[[-1.52752523 -1.09108945 -0.65465367 -0.21821789]
 [ 0.21821789  0.65465367  1.09108945  1.52752523]]
